      SUBROUTINE  MAKEFREQ(FREQTOTAL)
C
C     Routine for SCHED called by GETFREQ that calls the routines to create
C     the frequency settings used by L404B. This was original planned 
C     for the VNDA update.
C     All frequency settings generated by the following subroutines 
C     are meant to replace the VLBA settings in the frequency catalog
C     (freq_RDBE.dat). The catalog is still in use to include all 
C     non-VLBA frequencies and outlier VLBA settings that are not 
C     automated.
C     
C     In place for SCHED version 12. March 2023 AED.
C
      INCLUDE 'schfreq.inc'
C
      INTEGER           FREQTOTAL
C
      CALL WLOG( 0, 'MAKEFREQ: Create VLBA frequency settings' )
C     Create frequency settings for 20cm band
      CALL LBANDFREQ(FREQTOTAL)
C     Create frequency settings for 13cm band
      CALL SBANDFREQ(FREQTOTAL)
C     Create frequency settings for 6cm band
      CALL CBANDFREQ(FREQTOTAL)
C     Create frequency settings for 4cm band
      CALL XBANDFREQ(FREQTOTAL)
C     Create frequency settings for 2cm band
      CALL KUBANDFREQ(FREQTOTAL)
C     Create frequency settings for 1cm band
      CALL KBANDFREQ(FREQTOTAL)
C     Create frequency settings for 7mm band
      CALL QBANDFREQ(FREQTOTAL)
C     Create frequency settings for 3mm band
      CALL WBANDFREQ(FREQTOTAL)
C
C      
      END