#! /bin/csh
#
#  Update the catalogs from their constituent parts.
#
cd $SCHED/catalogs

echo Delete the old catalogs.
chmod u+w stations.dat
chmod u+w freq.dat
chmod u+w messages.txt
/bin/rm stations.dat
/bin/rm freq.dat
/bin/rm messages.txt
/bin/rm blankline
/bin/rm version

# Make a line to indicate the date the catalog was
# assembled. 

cat <<EOF > version

!  VERSION is the date and time when this catalog was
!  assembled from the master subcatalogs.
 
 VERSION = "`date +%Y%b%d-%T`"

EOF

echo Make a new Master_stations file.
cat Master_NRAO/stations_top.dat \
    version \
    Master_NRAO/stations_US.dat \
    Master_JIVE/stations_EVN.dat \
    Master_NRAO/stations_APT.dat \
    Master_NRAO/stations_DSN.dat \
    Master_ATNF/stations_ATNF.dat \
    Master_NRAO/stations_mm.dat \
    Master_NRAO/stations_geodesy.dat \
       > stations.dat

echo Make the new freq.dat file.
cat Master_NRAO/freq_top.dat \
    version \
    Master_NRAO/freq_VLBA.dat \
    Master_NRAO/freq_VLA.dat \
    Master_NRAO/freq_US.dat \
    Master_JIVE/freq_EVN.dat \
    Master_NRAO/freq_APT.dat \
    Master_NRAO/freq_DSN.dat \
    Master_ATNF/freq_ATNF.dat \
    Master_NRAO/freq_mm.dat \
    Master_NRAO/freq_geodesy.dat \
       > freq.dat

echo "   " > blankline
echo Make the new messages.txt file.
cat Master_NRAO/messages_NRAO.txt \
    blankline \
    Master_JIVE/messages_VEX.txt \
    blankline \
       > messages.txt
echo ++end >> messages.txt

echo 
echo Prohibit write on the new catalogs.
chmod u-w stations.dat
chmod u-w freq.dat
chmod u-w messages.txt
/bin/rm blankline
