#! /bin/csh

#  Make the tar files of a release.  
#  This script makes the src, aux, stdout, and rcwsrc files.
#  See package2 to make a complete installation file including
#  the executables.

# ==============================================================
#  Usage:  package vernum 
set schver=$1
# ==============================================================

set devrcw=$SCHED/TARFILES/rcwsrc.$schver.tar
set srctar=$SCHED/TARFILES/sched.src.$schver.tar
set auxtar=$SCHED/TARFILES/sched.aux.$schver.tar
set stdouttar=$SCHED/TARFILES/sched.stdout.$schver.tar

echo ' '
echo Deleting files with same names as this routine\'s output files.
/bin/rm $devrcw.gz
/bin/rm $srctar.gz
/bin/rm $auxtar.gz
/bin/rm $stdouttar.gz

echo ' '
echo Comparing versions in packagedev with versions in code:
echo Release version:
grep "VERSION=" src/Sched/sched.f | grep -v "C   "
echo Main SCHED code version in packagedev: $schver, code version:
grep "VERNUM =" src/Sched/versched.f
echo Version used for aux files and examples/Stdout: $schver
echo Vex and Plot versions:
grep "VEXVER =" src/Vex/vxlink.inc
grep "PLTVER =" src/Plot/plver.f

echo ' '
echo Deleting the \~ files.
/bin/rm -r *~ */*~ */*/*~ */*/*/*~

#  Note, on a Sun, the tar FF causes .o and core files to be ignored, 
#  among others.  That doesn't seem to be an option under Linux.
#  For Linux, try making a file with the files to exclude.

echo ' '
echo Making exclude file
/bin/rm src/objexclude
ls -1 src/*/*.o src/*/*/*.o | sed s:src/:./:g > src/objexclude

cd $SCHED/src
echo Write $devrcw
tar cf $devrcw --exclude Plot --exclude Vex \
        --exclude-from objexclude  .

#  Sched Plotstub Cit Jpl Jplstub Sla Makefile*
                   

cd $SCHED
/bin/rm objexclude
ls -1 src/*/*.o src/*/*/*.o > objexclude
echo Write $srctar 
tar -cf  $srctar --exclude-from objexclude  src bin/schclean

echo Write $auxtar
cd $SCHED
tar -cf  $auxtar \
     --exclude catalogs/Master_NRAO \
     --exclude catalogs/Master_ATNF \
     --exclude catalogs/Master_JIVE \
     catalogs  \
     setups            \
     doc/sched.tex     doc/sched         doc/makelinks    \
     doc/release_notes*     \
     examples/*.key    examples/*.set    examples/*.dat   \
     examples/Newstd   examples/Check*   examples/Verify  \
     examples/*.com    \
     bin/schclean      \
     package*          README            Release_instructions 

echo Write $stdouttar
cd $SCHED
tar -cf $stdouttar  examples/Stdout

echo ' '
echo Compressing the tar files.
cd $SCHED/TARFILES
gzip *.tar
cd $SCHED
