#!/bin/csh


#  Tasks that need to be done before a release.

Update VERSION in sched.f and the specific version in versched.f
Update the version on the manual first page in sched.tex

#  Get the latest versions from Huib and Franco.

#  Check the README and README.ftp files in $SCHED

#  Write a release note.

#  Update the manual and the web version.

#  First, update the examples embedded in the manual.

*********  Remove the 04Oct2004 warning from the top of sched.tex


cd $SCHED/doc
/bin/rm sched.tex.tmp
mv sched.tex sched.tex.tmp
inserttex 
sched.tex.tmp
sched.tex
 
#  Process the manual.  latex will probably need to be run up to
#  3 times to get all the links right.
#  The local icons switch keeps users from having to go to
#  NRAO for the up etc buttons (it didn't seem to be available
#  on my latex2html under RedHat 5.2 Linux on my home PC).
#  The -link option controls how deep the automatic contents 
#  go at each level.  Without it, the contents on the top level
#  page are long enought to frighten off users.

latex sched.tex
latex2html -local_icons -link 2 sched.tex

#  Update the setup files.

cd $SCHED/setups
makesetup

#  Update the catalogs from the masters.

cd $SCHED/catalogs
Update

Then hand update the VERSIONs in the source and locations files 
(at least until this is automated - I've asked John for automated versions).

#  Update the examples and clean up the area.
#  Check that testruns.out shows a clean comparison after Verify.

cd $SCHED/examples
Verify
Newstd
schclean "*"

#  Test the plot functions on egplan.key.  For 2002Jul02, there
#  was a bug in plotxy and plotuv that only showed up on a Sun.

#  Make the tar files.
#  First, move any files from TARFILES that should be archived to 
#  $SCHED/ARCHIVE.  If proper proceedures were followed last time, 
#  they should already be there.  At least each release should be 
#  archived for a few years, by which time it will be on a number 
#  of long term backup tapes.
#  Run "package" and "package2" for the current version.

package 6.0
package2 linux 6.0


#  Copy the release tar files to ARCHIVE.
#  Next time, I should try making this an actual script to see
#  if it can be truely automated.

#  Install the release in /users/cwalker/sched_sun
#  and compile using one of the sun machines.

#  Set the release date for file names.  Use the same as in package.

setenv NEWVER 6.0

#  Unpack the source distribution into /users/cwalker/sched_test and
#  test the compilation without the satellite stuff (clean out 
#  sched_test first if needed).

cd /users/cwalker/sched_test
setenv SCHED 
/bin/rm -r *
tar -xvf $SCHED/TARFILES/sched.aux.{$NEWVER}.tar.gz --gunzip
tar -xvf $SCHED/TARFILES/sched.src.{$NEWVER}.tar.gz --gunzip
tar -xvf $SCHED/TARFILES/sched.stdout.{$NEWVER}.tar.gz --gunzip
cd src
make -f Makefile.linux
cd ../examples
setenv SCHEDSAVE $SCHED
setenv SCHED /users/cwalker/sched_test
Verify
setenv SCHED $SCHEDSAVE

#  Make the release directory using the binary tar file.

mkdir /users/cwalker/files/sched_{$NEWVER}
cd /users/cwalker/files/sched_{$NEWVER}
tar -xvf $SCHED/TARFILES/sched.linux.{$NEWVER}.tar.gz --gunzip
mkdir bin/LINUX
mv bin/* bin/LINUX



#  Copy documentation to the web server master files on the mach disk
#  My cron jobs will move them to the main web server
#  Careful with the big delete (rm) below.
#  Someday, rationalize where the catalog stuff is located.
#
***********************************************   FIX ALL THIS FOR MACH ***
mkdir /users/cwalker/public_html/sched_{$NEWVER}
chmod u+w /users/cwalker/public_html/sched_{$NEWVER}/*
/bin/rm -r /users/cwalker/public_html/sched_{$NEWVER}/*
cp -r doc/sched /users/cwalker/public_html_{$NEWVER}/sched
/bin/rm /users/cwalker/public_html/sched_{$NEWVER}/sched/examples
/bin/rm /users/cwalker/public_html/sched_{$NEWVER}/sched/catalogs
cp catalogs/stations.dat /users/cwalker/public_html/sched_{$NEWVER}/stations
cp catalogs/sources.vlba /users/cwalker/public_html/sched_{$NEWVER}/sources
cp catalogs/freq.dat /users/cwalker/public_html/sched_{$NEWVER}/frequencies
mkdir /users/cwalker/public_html/sched_{$NEWVER}/sched/examples
cp examples/*.key /users/cwalker/public_html/sched_{$NEWVER}/sched/examples
cp examples/*.com /users/cwalker/public_html/sched_{$NEWVER}/sched/examples
cp examples/*.set /users/cwalker/public_html/sched_{$NEWVER}/sched/examples
mkdir /users/cwalker/public_html/sched_{$NEWVER}/sched/catalogs
cp catalogs/peak.cmd /users/cwalker/public_html/sched_{$NEWVER}/sched/catalogs




#  Copy to ftp  (FTP=/var/spool/ftp/pub)
#  No longer update skedconv or uptime.

cd $SCHED
/bin/rm $FTP/sched/README
/bin/rm $FTP/sched/sched.aux.{$NEWVER}.tar.gz
/bin/rm $FTP/sched/sched.src.{$NEWVER}.tar.gz
/bin/rm $FTP/sched/sched.stdout.{$NEWVER}.tar.gz
/bin/rm $FTP/staff/cwalker/Sched/rcwsrc.{$NEWVER}.tar.gz
/bin/rm $FTP/sched/intel-linux/sched.{$NEWVER}.intel-linux*
/bin/rm $FTP/sched/intel-linux/schclean
/bin/rm $FTP/sched/sun/sched.{$NEWVER}.sun*
/bin/rm $FTP/sched/sun/schclean
cp $SCHED/README.ftp $FTP/sched/README
cp $SCHED/TARFILES/sched.aux.{$NEWVER}.tar.gz     $FTP/sched
cp $SCHED/TARFILES/sched.src.{$NEWVER}.tar.gz     $FTP/sched
cp $SCHED/TARFILES/sched.stdout.{$NEWVER}.tar.gz  $FTP/sched
qcp $SCHED/TARFILES/rcwsrc.{$NEWVER}.tar.gz           $FTP/staff/cwalker/Sched
cp $SCHED/bin/sched   $FTP/sched/intel-linux/sched.{$NEWVER}.intel-linux
cp $SCHED/bin/schclean $FTP/sched/intel-linux
cd $FTP/sched/intel-linux
gzip sched.{$NEWVER}.intel-linux
cd /users/cwalker/sched_sun
cp bin/sched   $FTP/sched/sun/sched.{$NEWVER}.sun
cp bin/schclean $FTP/sched/sun
cd $FTP/sched/sun
gzip sched.{$NEWVER}.sun
cd $SCHED
#  Try to get executables for the other architectures.

#  Activate the new version.

cd /users/cwalker
/bin/rm sched
ln -s sched_{$NEWVER} sched



#  Send the email announcement to:
#  vlbi@nrao.edu,scistaff,analysts,pperley,vlbaops.

#  I think that is all.



