#! /bin/csh
#
#  Make some links that the html version of the manual uses.  They
#  should normally appear when the tar files are unloaded, but, if
#  they do not, this file can be used to extablish them.
#
cd $SCHED/doc/sched
ln -s ../../examples
ln -s ../../catalogs
ln -s ../../setups
