#!/bin/csh

#  Run makemake with the directory structures at the AOC.
#  The compilers new enough for the gif driver are in
#  /usr/local/compilers/rhel-5/x86_64/gcc-4.3.1
#  That path is incorporated in 
#  $SCHED/RELATED_CODE/PGPLOT/RCW_additions/sys_linux/gfortran_gccsp.conf

cd $SCHED/PGPLOT/linux64gfortran_5.3.1

$SCHED/PGPLOT/src5.3.1/makemake $SCHED/PGPLOT/src5.3.1 linux gfortran_gccsp


#  The make fails trying to make gpdemo1 because it can't find -lSystemStubs
#  but libpgplot.a libraries was made.  libcpgplot.a is awol.


