#!/bin/csh

#  Run makemake.  

cd $SCHED/PGPLOT/linux64gfortran_5.3.1

$SCHED/PGPLOT/src5.3.1/makemake $SCHED/PGPLOT/src5.3.1 linux gfortran_gcc


#  Prior to April 1, 2014, the standard gfortran (gcc) compiler at the AOC 
#  was too old for the gif driver of PGPLOT.  But there was another gfortran
#  available.  It was available at
#  /usr/local/compilers/rhel-5/x86_64/gcc-4.3.1
#  That path is incorporated in 
#  $SCHED/PGPLOT/RCW_additions/sys_linux/gfortran_gccsp.conf
#  That was invoked using the following instead of the equivalent line above.
#  $SCHED/PGPLOT/src5.3.1/makemake $SCHED/PGPLOT/src5.3.1 linux gfortran_gccsp





