#! /bin/csh
#
# Make sched on a linux box with the spice spacecraft tracking
# code available.
#
/bin/rm Makefile
ln -s Makefile.linux.spice Makefile
make
/bin/rm Makefile
ln -s Makefile.linux Makefile
