#!csh
#
#   Make a tar file of makesetup and required routines for Huib.
#
cp ../sublib/getline.f .
cp ../sublib/nxtwrd.f .
tar -cvf makesetup.tar compile makesetup.for getline.f nxtwrd.f
rm getline.f
rm nxtwrd.f

