#!/bin/tcsh

#  Delete the temporary files created by latex, htlatex etc.
#  May get errors if not all there.

#  Usage:  latexclean sched

/bin/rm $1.4ct
/bin/rm $1.4tc
/bin/rm $1.aux
/bin/rm $1.log
/bin/rm $1.tmp
/bin/rm $1.xref
/bin/rm $1.lg
/bin/rm $1.out
/bin/rm $1.dvi
/bin/rm $1.idv
/bin/rm $1.toc
#/bin/rm $1.css


