#!/bin/csh -f

# Run vexpeek on all the vex files in the directory.
# Run on a 64 bit Linux machine.

foreach file (*.vex)
  echo ' '
  echo $file
  /home/swc/software/VLBADIFX-TRUNK/bin/vexpeek $file
end
