#! /bin/csh

#  Copy current files for one example to Stdout to make new standard files.
#  Will need to do special files by hand.

echo 'If key file does not have same base name, copy it separately.'
echo 'May need to rename sched.runlog first'

/bin/cp $1.key      Stdout
/bin/cp $1.com      Stdout
/bin/cp $1.sum      Stdout
/bin/cp $1.tv2d     Stdout
/bin/cp $1crd.hn    Stdout
/bin/cp $1sch.hn    Stdout
/bin/cp $1.flag     Stdout
/bin/cp $1crd.gb    Stdout
/bin/cp $1.vex      Stdout
/bin/cp $1.oms      Stdout
/bin/cp $1.runlog   Stdout
