#!/bin/csh -f

# Run with source ./Verify if $SCHED is not the login value.


#  Shell script to verify operation of a version of SCHED.  It:
#     1.  Runs SCHED on the example input files.
#     2.  Compares the results with "standard" results in the "stdout" 
#         directories using diff.
#     Note - the plotting functions are not tested with this routine 
#            although the examples normally used to do that are tested
#            as regular examples.
#
#  To run, type "Verify SUN" if the executables in the bin/SUN directory
#  are to be used.
#
#  The -f above prevents resetting of $SCHED

#  Note, to test the crd files with cksched, login to a machine that can
#  run cksched and issue a command like:
# find . \( -name Stdout -prune \) -o -name "*crd.hn" -print -exec cksched '{}' \;



echo "==================================================="
echo "Be sure that the SCHED environment variable is set."
echo "Currently set to " $SCHED
echo "==================================================="
echo " "

# Set the directory of the SCHED executable to be tested:
setenv SCHBIN $SCHED/bin/$1
echo Running SCHED from $SCHBIN

# Set location of "standard" results.
if( -e $SCHED/examples/Stdout ) then
   setenv SCH_STDOUT $SCHED/examples/Stdout
else if( -e Stdout ) then
   setenv SCH_STDOUT Stdout
else
   echo Standard output file directory not found.
   exit
endif

# Set the location of the current $SCHED so that Verify can ignore
# differences in file paths on future comparisons.
source $SCH_STDOUT/SetSchedStd

#  First clean out any old files.
$SCHBIN/schclean "*"
/bin/rm doptgt.com
/bin/rm testruns.out

date > testruns.out

#  Now run SCHED on the examples and compare results with standards.
#  In alphabetical order for ease of comparison with ls etc.

echo All output will be in testruns.out

#  eg1024.key not done

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "***********" Processing eg1024.key "********************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < eg1024.key >> testruns.out
mv sched.runlog eg1024.runlog
./Check_results eg1024 mc $SCH_STDOUT eg1024.key >> testruns.out

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "***********" Processing eg2head.key "*******************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < eg2head.key >> testruns.out
mv sched.runlog n02l1.runlog
./Check_results n02l1 ef $SCH_STDOUT eg2head.key >> testruns.out

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "***********" Processing eg3mma.key "********************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < eg3mma.key >> testruns.out
mv sched.runlog eg3mma.runlog
./Check_results eg3mma pt $SCH_STDOUT eg3mma.key >> testruns.out

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "***********" Processing eg3mmb.key "********************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < eg3mmb.key >> testruns.out
mv sched.runlog eg3mmb.runlog
./Check_results eg3mmb pt $SCH_STDOUT eg3mmb.key >> testruns.out

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "***********" Processing eg3mmc.key "********************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < eg3mmc.key >> testruns.out
mv sched.runlog eg3mmc.runlog
./Check_results eg3mmc pt $SCH_STDOUT eg3mmc.key >> testruns.out

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "**************" Processing eg3mm_rd2.key "**************" | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < eg3mm_rd2.key  >> testruns.out
mv sched.runlog eg3mmrd2.runlog
./Check_results eg3mmrd2 pt $SCH_STDOUT eg3mm_rd2.key >> testruns.out

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "*************" Processing eg512g.key "******************"  | tee -a  testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < eg512g.key >> testruns.out
mv sched.runlog eg512g.runlog
./Check_results eg512g hn $SCH_STDOUT eg512g.key >> testruns.out

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "************" Processing eg512.key "********************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < eg512.key >> testruns.out
mv sched.runlog eg512.runlog
./Check_results eg512 hn $SCH_STDOUT eg512.key >> testruns.out

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "************" Processing eg5cm.key "********************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < eg5cm.key >> testruns.out
mv sched.runlog eg5cm.runlog
./Check_results eg5cm y $SCH_STDOUT eg5cm.key >> testruns.out

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "***********" Processing egglobal.key "******************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < egglobal.key >> testruns.out
mv sched.runlog ge001.runlog
./Check_results ge001 hn $SCH_STDOUT egglobal.key >> testruns.out

# egiii.key not done.  Key file deleted May 12, 2010.

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "**********" Processing egglobalOH.key "*****************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < egglobalOH.key >> testruns.out
mv sched.runlog eggl_oh.runlog
./Check_results eggl_oh hn $SCH_STDOUT egglobalOH.key >> testruns.out
echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "************" Processing eglst.key "********************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < eglst.key >> testruns.out
mv sched.runlog eglst.runlog
./Check_results eglst hn $SCH_STDOUT eglst.key >> testruns.out

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "***********" Processing egmk5vex.key "******************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < egmk5vex.key >> testruns.out
mv sched.runlog mk5vxg.runlog
./Check_results mk5vxg ef $SCH_STDOUT egmk5vex.key >> testruns.out

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "*************" Processing egOH.key "********************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < egOH.key >> testruns.out
mv sched.runlog egoh.runlog
./Check_results egoh hn $SCH_STDOUT egOH.key >> testruns.out

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "***********" Processing egplan.key "********************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < egplan.key >> testruns.out
mv sched.runlog egplan.runlog
./Check_results egplan hn $SCH_STDOUT egplan.key >> testruns.out

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "***********" Processing egvlba.key "********************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < egvlba.key >> testruns.out
mv sched.runlog egvlba.runlog
./Check_results egvlba hn $SCH_STDOUT egvlba.key >> testruns.out

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "*************" Processing eg24.key "********************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < eg24.key >> testruns.out
mv sched.runlog eg24.runlog
./Check_results eg24 hn $SCH_STDOUT eg24.key >> testruns.out

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "************" Processing egddc.key "********************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < egddc.key >> testruns.out
mv sched.runlog egddc.runlog
./Check_results egddc hn $SCH_STDOUT egddc.key >> testruns.out

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "************" Processing egddc2.key "********************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < egddc2.key >> testruns.out
mv sched.runlog egddc2.runlog
./Check_results egddc2 hn $SCH_STDOUT egddc2.key >> testruns.out

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "******" Processing piggyback.key for MARK5A"*************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
./runsch piggyback.key MARK5A >> testruns.out
mv sched.runlog piggya.runlog
./Check_results piggya hn $SCH_STDOUT piggyback.key >> testruns.out

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "******" Processing piggyback.key for MARK5C"*************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
./runsch piggyback.key MARK5C >> testruns.out
mv sched.runlog piggyc.runlog
./Check_results piggyc hn $SCH_STDOUT piggyback.key >> testruns.out

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "***********" Processing egcwide.key "*******************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < egcwide.key >> testruns.out
mv sched.runlog egcwide.runlog
./Check_results egcwide hn $SCH_STDOUT egcwide.key >> testruns.out

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "***********" Processing egrdbe2.key "*******************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < egrdbe2.key >> testruns.out
mv sched.runlog egrd2.runlog
./Check_results egrd2 hn $SCH_STDOUT egrdbe2.key >> testruns.out

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "***********" Processing rdbepfb.key "*******************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < rdbepfb.key >> testruns.out
mv sched.runlog rdbepfb.runlog
./Check_results rdbepfb hn $SCH_STDOUT rdbepfb.key >> testruns.out

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "************" Processing newsyn.key "********************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < newsyn.key >> testruns.out
mv sched.runlog newsyn.runlog
./Check_results newsyn la $SCH_STDOUT newsyn.key >> testruns.out

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "***********" Processing egcent.key "********************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < egcent.key >> testruns.out
mv sched.runlog egcent.runlog
./Check_results egcent hn $SCH_STDOUT egcent.key >> testruns.out

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "***********" Processing egdelzn.key "*******************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < egdelzn.key >> testruns.out
mv sched.runlog egdelzn.runlog
./Check_results egdelzn hn $SCH_STDOUT egdelzn.key >> testruns.out

# n2227.key USNO sample added Aug. 21, 2012.

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "***********" Processing n2227.key "*******************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < n2227.key >> testruns.out
mv sched.runlog n2227.runlog
./Check_results n2227 pt $SCH_STDOUT n2227.key >> testruns.out

# pfbsettst.key test PFB setups.

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "*********" Processing pfbsettst.key "*****************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < pfbsettst.key >> testruns.out
mv sched.runlog pfbtst.runlog
./Check_results pfbtst hn $SCH_STDOUT pfbsettst.key >> testruns.out

# tstsets.key test DDC setups.

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "*********" Processing tstsets.key "*******************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < tstsets.key >> testruns.out
mv sched.runlog tstsets.runlog
./Check_results tstsets hn $SCH_STDOUT tstsets.key >> testruns.out

#  egdifx.key deleted May 12, 2010.

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "***********" Processing egvsop.key "********************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < egvsop.key >> testruns.out
mv sched.runlog vt002.runlog
./Check_results vt002 hn $SCH_STDOUT egvsop.key >> testruns.out

#  EVN examples

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "******" Processing evn_cont_strong.key "****************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < evn_cont_strong.key >> testruns.out
mv sched.runlog eo999.runlog
./Check_results eo999 ef $SCH_STDOUT evn_cont_strong.key >> testruns.out

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "******" Processing evn_cont_strong_pol.key "************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < evn_cont_strong_pol.key >> testruns.out
mv sched.runlog eo902.runlog
./Check_results eo902 ef $SCH_STDOUT evn_cont_strong_pol.key >> testruns.out

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "*******" Processing evn_cont_weak_256.key "*************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < evn_cont_weak_256.key >> testruns.out
mv sched.runlog eo903.runlog
./Check_results eo903 ef $SCH_STDOUT evn_cont_weak_256.key >> testruns.out

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "*********" Processing evn_cont_weak_512.key "***********"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < evn_cont_weak_512.key >> testruns.out
mv sched.runlog eo904.runlog
./Check_results eo904 ef $SCH_STDOUT evn_cont_weak_512.key >> testruns.out

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "********" Processing evn_cont_weak_snap.key "***********"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < evn_cont_weak_snap.key >> testruns.out
mv sched.runlog eo905.runlog
./Check_results eo905 ef $SCH_STDOUT evn_cont_weak_snap.key >> testruns.out

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "*********" Processing evn_line_hi.key "*****************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < evn_line_hi.key >> testruns.out
mv sched.runlog eo906.runlog
./Check_results eo906 ef $SCH_STDOUT evn_line_hi.key >> testruns.out

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "*********" Processing evn_line_meth.key "***************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < evn_line_meth.key >> testruns.out
mv sched.runlog eo907.runlog
./Check_results eo907 ef $SCH_STDOUT evn_line_meth.key >> testruns.out

#  Back to other examples.

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "***********" Processing hsa21cm.key "*******************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < hsa21cm.key >> testruns.out
mv sched.runlog bw089.runlog
./Check_results bw089 hn $SCH_STDOUT hsa21cm.key >> testruns.out

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "***********" Processing hsa1cm.key "********************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < hsa1cm.key >> testruns.out
mv sched.runlog hsa1cm.runlog
./Check_results hsa1cm hn $SCH_STDOUT hsa1cm.key >> testruns.out

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "***********" Processing manual_1.key "*******************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < manual_1.key >> testruns.out
mv sched.runlog be001.runlog
./Check_results be001 hn $SCH_STDOUT manual_1.key >> testruns.out

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "***********" Processing manual_2.key "******************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < manual_2.key >> testruns.out
mv sched.runlog be002.runlog
./Check_results be002 hn $SCH_STDOUT manual_2.key >> testruns.out

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "**********" Processing manual_line.key "****************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < manual_line.key >> testruns.out
mv sched.runlog bd027.runlog
./Check_results bd027 hn $SCH_STDOUT manual_line.key >> testruns.out

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "**********" Processing manual_simp.key "****************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < manual_simp.key >> testruns.out
mv sched.runlog uvcov.runlog
./Check_results uvcov hn $SCH_STDOUT manual_simp.key >> testruns.out

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "************" Processing mt506.key "********************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < mt506.key >> testruns.out
mv sched.runlog mt506.runlog
./Check_results mt506 hn $SCH_STDOUT mt506.key >> testruns.out

echo "******************************************************"  >> testruns.out
echo "************" Processing dq415.key "********************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < dq415.key >> testruns.out
mv sched.runlog dq415.runlog
./Check_results dq415 hn $SCH_STDOUT dq415.key >> testruns.out

echo "******************************************************"  >> testruns.out
echo "************" Processing dqhiel.key "*******************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < dqhiel.key >> testruns.out
mv sched.runlog dqhiel.runlog
./Check_results dqhiel hn $SCH_STDOUT dqhiel.key >> testruns.out

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "***********" Processing planvla.key "*******************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < planvla.key >> testruns.out
mv sched.runlog yplan.runlog
./Check_results yplan y $SCH_STDOUT planvla.key >> testruns.out

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "***********" Processing vips11.key "********************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < vips11.key >> testruns.out
mv sched.runlog vips11.runlog
./Check_results vips11 hn $SCH_STDOUT vips11.key >> testruns.out

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "*************" Processing jvla.key "********************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < jvla.key >> testruns.out
mv sched.runlog jvla.runlog
./Check_results jvla hn $SCH_STDOUT jvla.key >> testruns.out

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "************" Processing hsaddc.key "*******************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < hsaddc.key >> testruns.out
mv sched.runlog hsaddc.runlog
./Check_results hsaddc hn $SCH_STDOUT hsaddc.key >> testruns.out

echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "**************" Processing lba.key "********************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < lba.key >> testruns.out
mv sched.runlog lba.runlog
./Check_results lba at $SCH_STDOUT lba.key >> testruns.out


echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "************" Processing lba_h2o.key "****************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < lba_h2o.key >> testruns.out
mv sched.runlog lbah2o.runlog
./Check_results lbah2o at $SCH_STDOUT lba_h2o.key >> testruns.out


echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "************" Processing lba_oh.key "*****************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < lba_oh.key >> testruns.out
mv sched.runlog lbaoh.runlog
./Check_results lbaoh at $SCH_STDOUT lba_oh.key >> testruns.out


echo " " >> testruns.out
echo " " >> testruns.out
echo "******************************************************"  >> testruns.out
echo "************" Processing lba_mk5.key "******************"  | tee -a testruns.out
echo "******************************************************"  >> testruns.out
$SCHBIN/sched < lba_mk5.key >> testruns.out
mv sched.runlog lba_mk5.runlog
./Check_results lba_mk5 at $SCH_STDOUT lba_mk5.key >> testruns.out

#  Check planet and satellite pointing, and creation of pointing
#  schedules.  The required ephemeris files and spice files are
#  only available at the AOC, so don't try elsewhere.

if ("$PLANET_DATA" == "/users/cwalker/PLANETDATA/Linux") then

   echo "******************************************************"  >> testruns.out
   echo "************" Processing doptg.com "********************" | tee -a testruns.out
   echo "******************************************************"  >> testruns.out
   sed s.\$SCHED/bin.\$SCHBIN.g  doptg.com > doptgt.com
   chmod +x doptgt.com
   source ./doptgt.com >> testruns.out
   /bin/rm doptgt.com
   mv sched.runlog ptg.runlog
   ./Check_results ptg hn $SCH_STDOUT doptg.com >> testruns.out

   echo "******************************************************"  >> testruns.out
   echo "************" Processing doptg2.com "*******************" | tee -a testruns.out
   echo "******************************************************"  >> testruns.out
   sed s.\$SCHED/bin.\$SCHBIN.g  doptg2.com > doptgt2.com
   chmod +x doptgt2.com
   source ./doptgt2.com >> testruns.out
   /bin/rm doptgt2.com
   mv sched.runlog ptg2.runlog
   ./Check_results ptg2 hn $SCH_STDOUT doptg.com >> testruns.out

   echo "******************************************************"  >> testruns.out
   echo "***********" Processing egsat.key "*********************"  | tee -a testruns.out
   echo "******************************************************"  >> testruns.out
   $SCHBIN/sched < egsat.key >> testruns.out
   mv sched.runlog egsat.runlog
   ./Check_results egsat pt $SCH_STDOUT egsat.key >> testruns.out

   echo "******************************************************"  >> testruns.out
   echo "***********" Processing tlesat.key "*********************"  | tee -a testruns.out
   echo "******************************************************"  >> testruns.out
   $SCHBIN/sched < tlesat.key >> testruns.out
   mv sched.runlog tlesat.runlog
   ./Check_results tlesat jm $SCH_STDOUT tlesat.key >> testruns.out

endif

echo ' --------------------------------------------------' >> testruns.out

date >> testruns.out
echo ' --------------------------------------------------' >> testruns.out

echo "===================================================="
echo "Examine   testruns.out   for results."
echo "  It will contain sched runtime output and comparison"
echo "  with standard results in directory Stdout."
echo "Do not worry about numbers differing in last digit -"
echo "  Some machines round differently"
echo "===================================================="
