#!/bin/csh -f

# Shell script to run a test much like what Verify does for
# all examples, but for just one key file.
# Run with three arguments, the key file, the comparison station,
# and the project code.
# For example:
# ./Verify_one egddc.key hn egddc

# Set the environment variables needed by Check_results.

echo Output in testone.out
setenv SCHED_STDOUT $SCHED/examples/Stdout
source $SCHED_STDOUT/SetSchedStd

# Reflect some of this.
echo $SCHED     > testone.out
echo $SCHED_STD >> testone.out
echo $SCHED_STD

# Delete previous files.
../bin/schclean $3
# Run sched:

../bin/sched < $1 >> testone.out

# Rename the runlog.

mv sched.runlog $3.runlog

# Use check_results to make the comparisons.

./Check_results $3 $2 $SCHED_STDOUT  $1 >> testone.out
