      SUBROUTINE FSFREQWR( KF, LOSUM, BBCFREQ, BBCBW,
     1     CRDN, CRDF, CRDB, CRDS, CRDLOSUM, CRSETC )
Cf2py intent(in) KF
Cf2py intent(out) LOSUM, BBCFREQ, BBCBW
Cf2py intent(out) CRDN, CRDF, CRDB, CRDS, CRDLOSUM, CRSETC
      INTEGER            KF
      DOUBLE PRECISION   LOSUM(32)
      DOUBLE PRECISION   BBCFREQ(32), BBCBW(32) 
      DOUBLE PRECISION   CRDF(32), CRDB(32), CRDLOSUM(32)
      INTEGER            CRDN, CRSETC(32)
      CHARACTER          CRDS(32)*1

      CALL FSFREQ( KF, LOSUM, BBCFREQ, BBCBW,
     1     CRDN, CRDF, CRDB, CRDS, CRDLOSUM, CRSETC )
      RETURN
      END
