      SUBROUTINE SUMDWRAP( ITEM, RET, LENGTH, LABFLAG )
      CHARACTER      ITEM*(*)
Cf2py CHARACTER(f2py_len=-1) ITEM
      INTEGER        LENGTH
      LOGICAL        LABFLAG
      CHARACTER*100  RET, SUMDESC
Cf2py intent(out) LENGTH, LABFLAG, RET
      RET = SUMDESC( ITEM, LENGTH, LABFLAG )
      RETURN
      END
