#! /bin/csh
#
# *** This is for the default gfortran compiler.
# *** This is ok after April 2014 at the AOC, unlike in the past.
#
# Use sed and the template Makefile.master to build a Makefile
# for a Linux 64bit machine using gfortran (gcc4+) without satellite tracking.
# This assumes that the PGPLOT libraries are in the location specified
# externally in the environment variable $PGPLOT_DIR.  That is the default
# in the Makefile.master.
#
# ************************************************************************
# *******  Be sure PGPLOT_DIR is set properly!                     *******
# *******  At the AOC with SCHED's version of pgplot, we use       *******
# *******  setenv PGPLOT_DIR $SCHED/PGPLOT/${Target}ortran_5.3.1/  *******
# *******  Also setenv PGPLOT_FONT $PGPLOT_DIR/grfont.dat          *******
# ************************************************************************
#
# RCW  Oct 30, 2008
# Updates RCW Jan. 31, 2012,   April 1, 2014.
#
# If anyone knows how to make proper configure scripts and would like
# to help by building one for SCHED, that would be much appreciated.
#

set Target=linux64gf

/bin/rm Makefile
/bin/rm -f make${Target}_sedscript

# Make a file for sed with all the required changes to Makefile.master
# The detailed specification of gfortran is required because the default gfortran
# at the AOC is older than what is required for the pgplot gif routines.

cat <<EOF >! make${Target}_sedscript
s:Makefile for SCHED:Temporary makefile for SCHED made by configure${Target}ortran:
s:#ARCHSED: ARCH = LINUX:
s:#FCSED: FC = gfortran -Wall -fimplicit-none -fno-backslash:
s:#XLDSED: XLD = -L/usr/lib64 -lX11:
s:#LDPGPLOTSED: LDPGPLOT = -L\$(LPGPLOT) -lpgplot:
s:#JPL_SRCS_SED: JPL_SRCS = \$(wildcard Jpl/*.f):
s:#SAT_SRCS_SED: SAT_SRCS = \$(wildcard Satstub/*.f):
s:#SATLDSED: SATLD = :
EOF

echo "s:BINDIR *= *../bin:&/${Target}:" >> make${Target}_sedscript
mkdir -p ../bin/${Target}

# Some changed stuff kept in case they are needed again.
#  Removed png from one line above.  Keep here in case needed.
#   s:#LDPGPLOTSED: LDPGPLOT = -L\$(LPGPLOT) -lpgplot -lpng:
#  If standard version of gfortran is ok:  
#   s:#FCSED: FC = gfortran -Wall -fimplicit-none -fno-backslash:


#  Run sed with the above file.

sed -f make${Target}_sedscript Makefile.master > Makefile
/bin/rm make${Target}_sedscript


#  When running make, you will see a variety of benign warnings that can be 
#  ignored.  The main one concerns character variables being truncated when
#  a variable of one length is set to equal a variable of another length.


echo '******************************************************************'
echo 'Before compiling or using SCHED,'
echo 'be sure PGPLOT_DIR and PGPLOT_FONT point to the right place (sched pgplot area?).'
echo '******************************************************************'
