#! /bin/csh
#  
#  Trying to make this work - January 2015  RCW and Bruce Rowen.
#  Update to be very much like configureLinux64gfortran.
#
# Use sed and the template Makefile.master to build a Makefile
# for 64-bit Linux machines with satellite tracking using gfortran
#
# Original:  RCW  Oct 30, 2008
# Updating Jan. 22, 2015 based on the configureLinux64gfortran that
# had been updated on Jan. 31, 2012,   April 1, 2014 by RCW.
#
# If anyone knows how to make proper configure scripts and would like
# to help by building one for SCHED, that would be much appreciated.
#

set Target=linuxsp64gf

setenv SEDFILE make${Target}_sedscript
/bin/rm Makefile
/bin/rm -f $SEDFILE

# Make a file for sed with all the required changes to Makefile.master
# Note that LPGPLOT is not needed for this case.

cat <<EOF >! $SEDFILE
s:Makefile for SCHED:Temporary makefile for SCHED made by configureLinuxSpice64gfortran:
s:#ARCHSED: ARCH = LINUX:
s:#FCSED: FC = gfortran -Wall -fimplicit-none -fno-backslash:
s:#XLDSED: XLD = -L/usr/lib64 -lX11:
s:#LDPGPLOTSED: LDPGPLOT = -L\$(LPGPLOT) -lpgplot:
s:#JPL_SRCS_SED: JPL_SRCS = \$(wildcard Jpl/*.f):
s:#SAT_SRCS_SED: SAT_SRCS = \$(wildcard Sat/*.f):
s:#SATLDSED: SATLD = ../lib/LINUX64GFORTRAN/spicelib.a ../lib/LINUX64GFORTRAN/support.a -lm:
EOF

echo "s:BINDIR *= *../bin:&/${Target}:" >> make${Target}_sedscript
mkdir -p ../bin/${Target}

#  Run sed with the above file.

sed -f $SEDFILE Makefile.master > Makefile
/bin/rm $SEDFILE

#  When running make, you will see a variety of benign warnings that can be 
#  ignored.  The main one concerns character variables being truncated when
#  a variable of one length is set to equal a variable of another length.

echo '******************************************************************'
echo 'Before compiling or using SCHED,'
echo 'be sure PGPLOT_DIR and PGPLOT_FONT point to the right place (sched pgplot area?).'
echo 'When testing at the AOC from the cwalker area, use (tchs):'
echo 'setenv PGPLOT_DIR /users/cwalker/files/sched_work/PGPLOT/linux64gfortran_5.3.1/'
echo 'setenv PGPLOT_FONT /users/cwalker/files/sched_work/PGPLOT/linux64gfortran_5.3.1/'
echo '******************************************************************'
