#! /bin/csh
#
# Use sed and the template Makefile.master to build a Makefile
# for 32-bit Ubuntu Hardy Linux machine without satellite tracking.
#
# RCW  Oct 30, 2008
#
# If anyone knows how to make proper configure scripts and would like
# to help by building one for SCHED, that would be much appreciated.
#
/bin/rm Makefile
/bin/rm -f makeubuntu.sedscript

# Make a file for sed with all the required changes to Makefile.master
# Note that LPGPLOT is not needed for this case.

cat <<EOF >! makeubuntu_sedscript
s:Makefile for SCHED:Temporary makefile for SCHED made by configureUbuntu:
s:#ARCHSED: ARCH = LINUX:
s:#FCSED: FC = g77 -Wall -Wimplicit -fno-backslash:
s:#XLDSED: XLD = -L/usr/lib -lX11:
s:#LDPGPLOTSED: LDPGPLOT = -L\$(LPGPLOT) -lpgplot -lpng:
s:#JPL_SRCS_SED: JPL_SRCS = \$(wildcard Jpl/*.f):
s:#SAT_SRCS_SED: SAT_SRCS = \$(wildcard Satstub/*.f):
s:#SATLDSED: SATLD = :
EOF

#  Run sed with the above file.

sed -f makeubuntu_sedscript Makefile.master > Makefile
/bin/rm makeubuntu_sedscript
