#! /bin/csh
#
# Special gfortran version to get a version of gfortran that is newer than
# the default at the AOC.  This is needed for pgplot.

# Use sed and the template Makefile.master to build a Makefile
# for a Linux 64bit machine using gfortran (gcc4+) without satellite tracking.
# This assumes that the PGPLOT libraries are in the location specified
# externally in the environment variable $PGPLOT_DIR.  That is the default
# in the Makefile.master.
#
# ************************************************************************
# *******  Be sure PGPLOT_DIR is set properly!                     *******
# *******  At the AOC with SCHED's version of pgplot, we use       *******
# *******  setenv PGPLOT_DIR $SCHED/PGPLOT/linux64gfortran_5.3.1/  *******
# ************************************************************************
#
# RCW  Oct 30, 2008
# Updates RCW Jan. 31, 2012.
#
# If anyone knows how to make proper configure scripts and would like
# to help by building one for SCHED, that would be much appreciated.
#
/bin/rm Makefile
/bin/rm -f makelinux64gf_sedscript

# Make a file for sed with all the required changes to Makefile.master
# The detailed specification of gfortran is required because the default gfortran
# at the AOC is older than what is required for the pgplot gif routines.

cat <<EOF >! makelinux64gf_sedscript
s:Makefile for SCHED:Temporary makefile for SCHED made by configureLinux64gfortran:
s:#ARCHSED: ARCH = LINUX:
s:#FCSED: FC = /usr/local/compilers/rhel-5/x86_64/gcc-4.3.1/bin/gfortran -Wall -fimplicit-none -fno-backslash:
s:#XLDSED: XLD = -L/usr/lib64 -lX11:
s:#LDPGPLOTSED: LDPGPLOT = -L\$(LPGPLOT) -lpgplot:
s:#JPL_SRCS_SED: JPL_SRCS = \$(wildcard Jpl/*.f):
s:#SAT_SRCS_SED: SAT_SRCS = \$(wildcard Satstub/*.f):
s:#SATLDSED: SATLD = :
EOF

# Some changed stuff kept in case they are needed again.
#  Removed png from one line above.  Keep here in case needed.
#   s:#LDPGPLOTSED: LDPGPLOT = -L\$(LPGPLOT) -lpgplot -lpng:
#  If standard version of gfortran is ok:  
#   s:#FCSED: FC = gfortran -Wall -fimplicit-none -fno-backslash:


#  Run sed with the above file.

sed -f makelinux64gf_sedscript Makefile.master > Makefile
/bin/rm makelinux64gf_sedscript


#  When running make, you will see a variety of benign warnings that can be 
#  ignored.  The main one concerns character variables being truncated when
#  a variable of one length is set to equal a variable of another length.


echo '******************************************************************'
echo 'Before compiling or using SCHED,'
echo 'be sure PGPLOT_DIR points to the right place (sched pgplot area?).'
echo '******************************************************************'
