#! /bin/csh
#
# Use sed and the template Makefile.master to build a Makefile
# for a Linux 64bit machine using gfortran (gcc4+) without satellite tracking.
# This uses SCHED's local version of PGPLOT.
#
# RCW  Oct 30, 2008
#
# If anyone knows how to make proper configure scripts and would like
# to help by building one for SCHED, that would be much appreciated.
#
/bin/rm Makefile
/bin/rm -f makelinux64gf_sedscript

# Make a file for sed with all the required changes to Makefile.master

cat <<EOF >! makelinux64gf_sedscript
s:Makefile for SCHED:Temporary makefile for SCHED made by configureLinux64gfortran:
s:#ARCHSED: ARCH = LINUX:
s:#FCSED: FC = /usr/local/compilers/rhel-5/x86_64/gcc-4.3.1/bin/gfortran -Wall -fimplicit-none -fno-backslash:
s:#XLDSED: XLD = -L/usr/lib64 -lX11:
s:#LDPGPLOTSED: LDPGPLOT = -L\$(LPGPLOT) -lpgplot:
s:#JPL_SRCS_SED: JPL_SRCS = \$(wildcard Jpl/*.f):
s:#SAT_SRCS_SED: SAT_SRCS = \$(wildcard Satstub/*.f):
s:#SATLDSED: SATLD = :
EOF
#  Removed png from one line above.  Keep here in case needed.
#  s:#LDPGPLOTSED: LDPGPLOT = -L\$(LPGPLOT) -lpgplot -lpng:


#  Run sed with the above file.

sed -f makelinux64gf_sedscript Makefile.master > Makefile
/bin/rm makelinux64gf_sedscript


#  When running make, you will see a variety of benign warnings that can be 
#  ignored.  The main one concerns character variables being truncated when
#  a variable of one length is set to equal a variable of another length.


echo '******************************************************************'
echo 'Before compiling or using SCHED,'
echo 'be sure PGPLOT_DIR points to the right place (sched pgplot area?).'
echo '******************************************************************'
