#! /bin/csh
#
# Use sed and the template Makefile.master to build a Makefile
# for 64-bit Linux machines with satellite tracking.
#
# RCW  Oct 30, 2008
#
# If anyone knows how to make proper configure scripts and would like
# to help by building one for SCHED, that would be much appreciated.
#
set Target=linuxSpice64

/bin/rm Makefile
/bin/rm -f make${Target}.sedscript

# Make a file for sed with all the required changes to Makefile.master
# Note that LPGPLOT is not needed for this case.

cat <<EOF >! make${Target}_sedscript
s:Makefile for SCHED:Temporary makefile for SCHED made by configure${Target}:
s:#ARCHSED: ARCH = LINUX:
s:#FCSED: FC = g77 -Wall -Wimplicit -fno-backslash:
s:#XLDSED: XLD = -L/usr/lib64 -lX11:
s:#LDPGPLOTSED: LDPGPLOT = -lpgplot -lpng:
s:#JPL_SRCS_SED: JPL_SRCS = \$(wildcard Jpl/*.f):
s:#SAT_SRCS_SED: SAT_SRCS = \$(wildcard Sat/*.f):
s:#SATLDSED: SATLD = ../lib/LINUX64/spicelib.a ../lib/LINUX64/support.a -lm:
EOF

echo "s:BINDIR *= *../bin:&/${Target}:" >> make${Target}_sedscript
mkdir -p ../bin/${Target}

#  Run sed with the above file.

sed -f make${Target}_sedscript Makefile.master > Makefile
/bin/rm make${Target}_sedscript
