#! /bin/csh
#
# Make SCHED on a ubuntu linux box without the spice spacecraft tracking
# code available.  This is so close to Makefile.linux (Red Hat Enterprise
# Linux) that I'll just make some changes with sed rather than linking
# to a separate makefile.
#
/bin/rm Makefile
/bin/rm makeubuntu_sedscript

cat <<EOF >! makeubuntu_sedscript
s/Makefile for SCHED/Temporary makefile for SCHED made by MakeUbuntu/
s/#XLD =      /XLD =       /
s&XLD = \-L/usr/lib64&#XLD = -L/usr/lib64&
s&#LPGPLOT = /usr/local/lib&LPGPLOT = /usr/local/lib&
s&#LPGPLOT = /usr/local/lib&LPGPLOT = /usr/local/lib&
s&LDPGPLOT = \-lpgplot \-lpng&#LDPGPLOT = \-lpgplot \-lpng&
s&#LDPGPLOT = \-L\$(LPGPLOT) \-lpgplot \-lpng&LDPGPLOT = \-L\$(LPGPLOT) \-lpgplot&
EOF

sed -f makeubuntu_sedscript Makefile.linux > Makefile

make
