#! /bin/csh
#
#
# Make sure that the /opt/intel/fc/9.0/bin/ifortvars.csh has been
# invoked before attempting to compile Sched.
#
# Make sched on a linux box without the spice spacecraft tracking
# code available.
#
/bin/rm Makefile
ln -s Makefile.intel Makefile
make
