      INTEGER FUNCTION VMSHLP(TOPIC)
      CHARACTER*(*) TOPIC
      CHARACTER*128 LIB
      INTEGER IER, IC
      INTEGER LBR$OUTPUT_HELP, LIB$FIND_FILE
      EXTERNAL LIB$PUT_OUTPUT, LIB$GET_INPUT
C
      IER = LIB$FIND_FILE('VLBHELP:VLBI.HLB', LIB, IC)
      IF (IER) THEN
          IER = LBR$OUTPUT_HELP(LIB$PUT_OUTPUT, , TOPIC, 
     1            'VLBHELP:VLBI.HLB', , LIB$GET_INPUT)
      END IF
      VMSHLP = IER
      END
