#!/bin/csh -f

# Run cksched on crd files from all examples
# Log into shire to do this.
# It is probably best to do in the Stdout area.


foreach file (*crd.*)
  echo ' '
  echo $file
  cksched $file
end


