#! /bin/csh

#  Allow Verify to ignore different $SCHEDs in the examples
#  and the Stdout versions.

/bin/rm Stdout/SetSchedStd
cat <<EOF > Stdout/SetSchedStd
#! /bin/csh
  setenv SCHED_STD $SCHED
EOF

#  Copy current files to Stdout to make new standard files.

/bin/cp *.key      Stdout
/bin/cp *.com      Stdout
/bin/cp *.sum      Stdout
/bin/cp *crd.hn    Stdout
/bin/cp *sch.hn    Stdout
/bin/cp *.flag     Stdout
/bin/cp *obs.y     Stdout
/bin/cp *crd.y     Stdout
/bin/cp *sch.y     Stdout
/bin/cp *crd.gb    Stdout
/bin/cp *sch.gb    Stdout
#/bin/cp *obs.gb    Stdout  Don't have in examples any more.
/bin/cp *obs.mc    Stdout
/bin/cp *.skd      Stdout
/bin/cp *.oms      Stdout
/bin/cp *.runlog   Stdout
/bin/cp eo*sch.ef Stdout
/bin/cp ce001crd.pt Stdout
/bin/cp ce001sch.pt Stdout
/bin/cp eg3mm*crd.pt Stdout
/bin/cp eg3mm*sch.pt Stdout
/bin/cp n02l1sch.ef Stdout
/bin/cp mk5vxsch.ef Stdout
/bin/cp egsatcrd.pt Stdout
/bin/cp egsatsch.pt Stdout
/bin/cp egmk5crd.pt Stdout
/bin/cp egmk5sch.pt Stdout
